export const foodData = [
  {
    id: 1,
    title: "Classic Spaghetti Bolognese",
    prepTime: "15 minutes",
    cookTime: "30 minutes",
    description: "A timeless Italian dish featuring hearty ground beef and flavorful tomato sauce served over perfectly cooked spaghetti.",
    nutritionFacts: {
      servingSize: "1 plate",
      calories: 450,
      totalFat: "18g",
      protein: "20g",
    },
    ingredients: [
      "250g ground beef",
      "1 onion, finely chopped",
      "2 cloves of garlic, minced",
      "400g canned crushed tomatoes",
      "2 tbsp tomato paste",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "250g spaghetti",
      "Grated Parmesan cheese (for serving)",
    ],
    instructions: [
      "Heat oil in a pan, add onion and garlic, and sauté until translucent.",
      "Add ground beef and cook until browned. Drain excess fat.",
      "Stir in crushed tomatoes, tomato paste, oregano, salt, and pepper. Simmer for 20 minutes.",
      "Meanwhile, cook spaghetti according to package instructions. Drain.",
      "Serve the Bolognese sauce over cooked spaghetti, topped with grated Parmesan cheese.",
    ],
    image:
      "https://i.pinimg.com/236x/35/db/dd/35dbddf1887bf024d74eb1e30e7ac2f7.jpg",
      
  },
  {
    id: 2,
    title: "Roast Chicken with Vegetables",
    prepTime: "20 minutes",
    cookTime: "1.5 - 2 hours",
    description: "A comforting roasted chicken dish accompanied by tender vegetables, perfect for a hearty and wholesome meal.",
    nutritionFacts: {
      servingSize: "1 serving",
      calories: 350,
      totalFat: "12g",
      protein: "30g",
    },
    ingredients: [
      "1 whole chicken (about 4 lbs)",
      "4 carrots, peeled and chopped",
      "4 potatoes, peeled and chopped",
      "1 onion, quartered",
      "4 cloves of garlic, minced",
      "2 tbsp olive oil",
      "1 tsp dried rosemary",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat the oven to 375°F (190°C).",
      "Rub the chicken with olive oil, rosemary, salt, and pepper.",
      "Place chicken in a roasting pan, surrounded by chopped vegetables and onion.",
      "Roast for about 1.5 to 2 hours, or until chicken is cooked through and vegetables are tender.",
    ],
    image:
      "https://i.pinimg.com/236x/c6/47/a4/c647a4084676a4b4b5138bddc168d30f.jpg",
  },
  {
    id: 3,
    title: "Vegetable Stir-Fry",
    prepTime: "15 minutes",
    cookTime: "15 minutes",
    description: "A quick and healthy stir-fry loaded with colorful vegetables and savory flavors.",
    nutritionFacts: {
      servingSize: "1 bowl",
      calories: 250,
      totalFat: "10g",
      protein: "8g",
    },
    ingredients: [
      "Assorted vegetables (e.g., bell peppers, broccoli, carrots, snap peas)",
      "2 tbsp vegetable oil",
      "2 cloves of garlic, minced",
      "1 tsp grated ginger",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp sesame oil",
      "Optional: tofu, chicken, or beef slices",
    ],
    instructions: [
      "Heat oil in a wok or pan over high heat.",
      "Add garlic and ginger, and sauté for a minute.",
      "Add vegetables and stir-fry for a few minutes until slightly tender.",
      "Add soy sauce, oyster sauce, and sesame oil. Stir-fry for another minute.",
      "Serve over rice or noodles.",
    ],
    image:
      "https://i.pinimg.com/236x/21/b7/11/21b7111f61d453d8bf5b942ff58cc8d9.jpg",
  },
  {
    id: 4,
    title: "Caprese Salad",
    prepTime: "10 minutes",
    cookTime: "0 minutes",
    description: "A simple and refreshing salad made with fresh mozzarella, tomatoes, and basil, drizzled with olive oil and balsamic vinegar.",
    nutritionFacts: {
      servingSize: "1 serving",
      calories: 180,
      totalFat: "12g",
      protein: "8g",
    },
    ingredients: [
      "Fresh mozzarella cheese, sliced",
      "Fresh tomatoes, sliced",
      "Fresh basil leaves",
      "Extra-virgin olive oil",
      "Balsamic vinegar",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Arrange alternating slices of mozzarella, tomato, and basil on a serving platter.",
      "Drizzle with olive oil and balsamic vinegar.",
      "Season with salt and pepper. Serve as a light appetizer or side dish.",
    ],
    image:
      "https://i.pinimg.com/236x/0c/5e/8b/0c5e8b704ae00ef689745d3c19c878d3.jpg",
  },
  {
    id: 5,
    title: "Chocolate Chip Cookies",
    prepTime: "15 minutes",
    cookTime: "10 minutes",
    description: "Classic homemade chocolate chip cookies that are soft, chewy, and irresistibly delicious.",
    nutritionFacts: {
      servingSize: "1 cookie",
      calories: 150,
      totalFat: "8g",
      protein: "2g",
    },
    ingredients: [
      "1 cup (2 sticks) unsalted butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup packed brown sugar",
      "1 tsp vanilla extract",
      "2 large eggs",
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 cups semisweet chocolate chips",
    ],
    instructions: [
      "Preheat the oven to 375°F (190°C).",
      "In a large bowl, cream together butter, granulated sugar, brown sugar, and vanilla extract.",
      "Beat in eggs, one at a time, until well combined.",
      "In a separate bowl, whisk together flour, baking soda, and salt. Gradually add to the wet ingredients and mix until just combined.",
      "Stir in chocolate chips.",
      "Drop spoonfuls of dough onto baking sheets. Bake for 9-11 minutes, or until golden brown.",
      "Allow cookies to cool on baking sheets for a few minutes before transferring to wire racks to cool completely.",
    ],
    image:
      "https://i.pinimg.com/236x/36/ec/a0/36eca002284ca60cac0bd7bfb5509325.jpg",
  },
  {
    id: 6,
    title: "Grilled Salmon with Asparagus",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    description: "Delicious grilled salmon paired with tender asparagus, a perfect combination for a healthy and flavorful dish.",
    nutritionFacts: {
      servingSize: "1 serving",
      calories: 300,
      totalFat: "15g",
      protein: "30g",
    },
    ingredients: [
      "4 salmon fillets",
      "1 bunch of asparagus, trimmed",
      "2 tbsp olive oil",
      "1 lemon, sliced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat the grill to medium-high heat.",
      "Rub salmon fillets with olive oil, salt, and pepper.",
      "Place salmon and asparagus on the grill. Cook salmon for about 4-5 minutes on each side.",
      "Grill asparagus for 2-3 minutes until tender.",
      "Serve salmon and asparagus together with lemon slices.",
    ],
    image:
      "https://i.pinimg.com/236x/78/b8/a8/78b8a8068cae03ae1918c553ebb5b59f.jpg",
  },
  {
    id: 7,
    title: "Mediterranean Chickpea Salad",
    prepTime: "15 minutes",
    cookTime: "0 minutes",
    description: "A refreshing Mediterranean salad featuring chickpeas, fresh vegetables, and a zesty dressing.",
    nutritionFacts: {
      servingSize: "1 bowl",
      calories: 200,
      totalFat: "8g",
      protein: "6g",
    },
    ingredients: [
      "1 can (15 oz) chickpeas, drained and rinsed",
      "1 cucumber, diced",
      "1 red bell pepper, diced",
      "1 cup cherry tomatoes, halved",
      "1/4 cup red onion, finely chopped",
      "1/4 cup feta cheese, crumbled",
      "2 tbsp olive oil",
      "2 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine chickpeas, cucumber, bell pepper, tomatoes, and red onion.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.",
      "Pour the dressing over the salad and toss to combine.",
      "Top with crumbled feta cheese.",
      "Serve as a refreshing and healthy side dish.",
    ],
    image:
      "https://i.pinimg.com/236x/74/26/19/742619e19f3d477cacf7a3542acba592.jpg",
  },
];
